version: '3'
services:
  db:
    build: ./db
    restart: always
    env_file:
      - ./.env
    ports: 
      - "3306:3306"
    networks: 
      - dev

  api:
    build: ./project-planner-api
    restart: always
    develop:
      watch:
        - action: sync
          path: ./project-planner-api
          target: /api
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    env_file:
      - ./.env
    ports: 
      - "3000:3000"
    networks: 
      - dev
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: rmsoft
    ports:
      - "8080:8080"
    networks:
      - dev
    depends_on:
      - db


networks:
  dev:
    driver: bridge